/*
 * ultrasonic.c
 *
 *  Created on: Oct 15, 2022
 *      Author: dell
 */

#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h>

uint8 g_edgeCount = 0;
uint16 g_echo_time = 0;


/*
 * Description :
 * Initialize the ULTRASONIC sensor:
 * 1. Setup the ULTRASONIC sensor pins directions by use the GPIO driver.
 * 2. Initialize the ICU driver.
 * 3. Setup the ICU call back function.
 */
void Ultrasonic_init(void){
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	Icu_init(&Icu_Config);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,PIN_OUTPUT);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_LOW);
	GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT_ID,ULTRASONIC_ECHO_PIN_ID,PIN_INPUT);
}


/*
 * Description :
 * Send the Trigger pulse to the Ultrasonic sensor from the MC.
 * Transmit at least 10 us trigger pulse using a delay.
 */
void Ultrasonic_Trigger(void){
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 * return distance variable (echo time)
 */
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	return (0.0174*g_echo_time);
}


/*
 * Description :
 *  This is the call back function called by the ICU driver.
 *  calculate the high time (pulse time) generated by  the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{
			/* Store the High time value */
			g_echo_time = Icu_getInputCaptureValue();
			/* Detect rising edge */
			Icu_setEdgeDetectionType(RISING);
			g_edgeCount = 0;
		}

}



