/*
 * ultrasonic.h
 *
 *  Created on: Oct 15, 2022
 *      Author: dell
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

/* ULTRASONIC HW Ports and Pins IDs */
#define ULTRASONIC_TRIGGER_PORT_ID		PORTB_ID
#define ULTRASONIC_TRIGGER_PIN_ID		PIN5_ID


#define ULTRASONIC_ECHO_PORT_ID			PORTD_ID
#define ULTRASONIC_ECHO_PIN_ID			PIN6_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ULTRASONIC sensor
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Send the Trigger pulse to the Ultrasonic sensor from the MC.
 */
void Ultrasonic_Trigger(void);

/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * return distance variable (echo time)
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 *  The call back function called by the ICU driver.
 *  calculate the high time generated by  the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);



#endif /* ULTRASONIC_H_ */
